### ISSUE TITLE
The score record length of a single scorer did not match the number of sleep stages in PSG

### ISSUE THREAD

**Issue by xiaoshijiu1999** [Dreem-Organization/dreem-learning-evaluation#2]
Thank you very much for making this data set public. But I ran into a problem using the results of individual scores. The record length of a single score is much larger than the total number of sleep stages in the PSG data in the H5 file. Can you provide the scoring record of a single scorer that matches the length of PSG data in the H5 file? Thank you very much!

**Comment by GoMapur** [comment]
@xiaoshijiu1999 Hi, I’m encountering the same issue. Could you share how you handled it?
