### ISSUE TITLE
N-1 scorers in consensus

### ISSUE THREAD

**Issue by n-grieger** [Dreem-Organization/dreem-learning-evaluation#3]
Hi @vthorey and @AntoineGuillot2! Thank you for providing this dataset, it's one of the only datasets I found that has annotations from multiple scorers :+1: 
I was looking through your code, because I wanted to recreate your consensus. As far i understand your code you create the consensus in the following lines: 
https://github.com/Dreem-Organization/dreem-learning-evaluation/blob/1e4c142d84634b60898845243b01b81d7eb4acec/evaluation.py#L337-L343
Why are you only using the scores of N-1 scorers to create the consensus here? Would it not be better to use the scores of all 5 scorers?
Thanks!

**Comment by AntoineGuillot2** [comment]
Hi @n-grieger,
For evaluation, we use the consensus of the four best scorers (when compared with other scorers). There are two main reasons: 
- each scorer is also compared to the four other scorers
- this may help us discard a very poor scoring on a specific recording.

**Comment by n-grieger** [comment]
@AntoineGuillot2 Great, thank you for the explanation!
